### ISSUE TITLE
For some videos the plugin does not work

### ISSUE THREAD

**Issue by csuarez** [WebDevStudios/Automatic-Featured-Images-from-Videos#21]
For some videos the plugins is not working. Some of the videos:

- https://www.youtube.com/watch?v=3M_Gg1xAHE4
- https://www.youtube.com/watch?v=33k9nQWwjIM
- https://www.youtube.com/watch?v=dw7aUMz46Hs
- https://www.youtube.com/watch?v=e0jWG0ZY8hI

In all the post the unique content are the YouTube URLs as pasted above.

**Comment by tw2113** [comment]
Can you try again with those videos and the version of the plugin from here on GitHub? 

Use this download of the code:
https://github.com/WebDevStudios/Automatic-Featured-Images-from-Videos/archive/master.zip

Related, I believe I did some small patches related to this type of issue in July, but due to where I was at the time geographically, i wasn't able to release it to wordpress.org.

**Comment by absentio** [comment]
This version is now working. I've had the same problem as the user that reported the issue. Thank you.

**Comment by tw2113** [comment]
This should be in the release version now.

**Comment by csuarez** [comment]
Thanks for the fast response!

**Comment by tw2113** [comment]
@csuarez if you could, please confirm that 1.0.3 from wordpress.org works as expected with those videos

**Comment by csuarez** [comment]
@tw2113 Sorry for the late response. I've tested all our broken posts and now they work fine. Thanks! 😄

**Comment by tw2113** [comment]
Awesome, thanks for helping confirm.
