### ISSUE TITLE
Bulk Processing - "Processing" indicator never goes away

### ISSUE THREAD

**Issue by CrowdForge** [WebDevStudios/Automatic-Featured-Images-from-Videos#37]
After the process is complete, the 'Processing' indicator is never removed or changed to reflect the process is complete.

**Comment by binarygary** [comment]
@CrowdForge thanks for digging into this branch.
This bug might be a result of how the processing is actually handled.  
The bulk process processes the first 10 posts that apply and then if there are any remaining posts to process it reschedules itself to run 10 minutes later.  
During that time it will show 'Processing'.  

The logic currently is set to not display a button if there are no posts that need to be processed.

I wonder 2 things:
First, did it actually process **all** the posts?  
Second, what criteria did you use to determine that it was done processing?  (was there still a scheduled task?)

**Comment by CrowdForge** [comment]
@binarygary I cheated. I edited the ajax to console.log('all done'); when it ran out of work.

**Comment by CrowdForge** [comment]
To clarify though, before I used the code to make sure it was reaching the end I did try just letting it set for a while. It was about an hour.

**Comment by binarygary** [comment]
I was super conservative in with the processing logic because this plugin is on .org 
I'm concerned about the potential shared hosting it may be used on.

Logic is as follows:
* Grab 10 posts and check for video.  
* If they have a video, try and grab the thumbnail.
* Check and see if there are more posts that haven't been processed. 
* If so, schedule it to batch again in 10 minutes. (ten minutes is a minimum in wp_schedule_single_event())...actually now that I read that I think that that only applies when scheduling multiple events of the same name.  I wonder if it will still be an issue if it tries to schedule itself within the event it fired.

**Comment by tw2113** [comment]
From what I can see with the present state, if we're set to "do_not_process" no button is appended. So the issue is technically resolved.
