### ISSUE TITLE
Why isn't the last version on wordpress.org

### ISSUE THREAD

**Issue by absentio** [WebDevStudios/Automatic-Featured-Images-from-Videos#48]
When I try to install this plugin on wordpress it says version 1.0.3 but here last stable is 1.1.0. What's the problem?

**Comment by tw2113** [comment]
The reason the versions are different are because we had done work that we intended to be 1.1.0 but had not finalized it yet.

With this plugin at least, we consider the version on WordPress.org to be the official released version, and what we have in the repo here to be "in the works" outside of the git tags.

As a personal aside, I am wanting to get time carved out so that I could take care of finalizing 1.1.0 and get it out the door for everyone. Just haven't done so quite yet.

**Comment by tw2113** [comment]
This has been pushed up to live since. Thanks.
